config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :uploads, only: [:new, :create, :index]
  resources :products, only: :index

  root 'uploads#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  paginates_per 100

  belongs_to :supplier, foreign_key: :supplier_uniq_ident, primary_key: :uniq_ident

  validates :sku, presence: true, uniqueness: true, length: { in: 2..255 }
  validates :supplier_uniq_ident, presence: true, length: { in: 2..255 }
  validates *((0..5).map{|i| "field_#{i}"}), length: { maximum: 255 }
  validates :price, numericality: true, length: { maximum: 9 }, 
               format: { with: /\A\d+(\.{1}\d{1,2})?\Z/ }
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_many :products, foreign_key: :uniq_ident, primary_key: :supplier_uniq_ident

  validates :uniq_ident, uniqueness: true, presence: true, length: { in: 2..255 }
  validates :name, presence: true, length: { in: 2..255 }
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  paginates_per 20

  DATA_TYPES = [:products, :suppliers]
  DATA_TYPES_COLUMNS_SIZE = { products: 8, suppliers: 1 }
  DATA_DELIMITER = '\xa6'

  has_attached_file :file
  validates_attachment :file, presence: true,
    content_type: { content_type: "text/csv" },
    size: { in: 0..100.megabytes }
  validates :data_type, inclusion: { in: ['products', 'suppliers'] }
  validate :partial_file_validation, on: :create

  after_commit :start_background_job, on: :create

  state_machine initial: :new do
    before_transition   on: :start,            do: 'upload_to_temp_table!'
    before_transition   on: :insert,           do: 'insert_data!'
    after_transition    on: [:finish, :broke],  do: 'clean_temp_data!'
    after_failure       on: :all,              do: 'broke!'

    event :start do
      transition :new => :uploaded
    end

    event :insert do
      transition :uploaded => :inserted
    end

    event :finish do
      transition :inserted => :finished
    end

    event :broke do
      transition [:new, :uploaded, :inserted, :finished] => :broken
    end
  end

  private
  
  def partial_file_validation
    @test_file = Tempfile.new('test_temp', '/tmp')
    begin
      open(file.queued_for_write[:original].path).first(10).each do |line|
        raise 'broken columns number' if line.scan(/¦/).size != 
                                           DATA_TYPES_COLUMNS_SIZE[:"#{data_type}"]
        @test_file.puts(line)
      end
      FileUtils.chmod(0755, @test_file)
      upload_to_temp_table!
      create_test_table!
      insert_data!(false)
      clean_temp_data!
    rescue => e
      errors.add(:broken_file, "Can't upload file because of reason: #{e}")
    ensure
      @test_file.close
      @test_file.unlink
    end
    @test_file = nil
  end

  def upload_to_temp_table!
    clean_temp_data!
    execute_with_detect_failures(send("#{data_type}_create_temp_table_query"))
    execute_with_detect_failures(copy_query)
  end

  def insert_data!(test=false)
    execute_with_detect_failures(send("insert_#{data_type}_parsed_data", test))
  end

  def clean_temp_data!
    execute_with_detect_failures(%Q[ DROP TABLE IF EXISTS temp_upload_table_#{id}; ])
    execute_with_detect_failures(%Q[ DROP TABLE IF EXISTS temp_test_#{data_type}; ])
  end

  def execute_with_detect_failures(query)
    begin
      ActiveRecord::Base.connection.execute(query)
    rescue => e
      parse_errors = "Upload to temp table error: #{e}"
      raise e if @test_file
    end
    parse_errors.blank?
  end

  def products_create_temp_table_query
    %Q[ CREATE TABLE temp_upload_table_#{id} 
          ( id SERIAL,
            SKU varchar(255) NOT NULL, SUPPLIER_UNIQ_IDENT char(255) NOT NULL,
            FIELD_0 char(255), FIELD_1 char(255), FIELD_2 char(255), 
            FIELD_3 char(255), FIELD_4 char(255), FIELD_5 char(255),
            PRICE NUMERIC(8,2) ); ]
  end

  def suppliers_create_temp_table_query
    %Q[ CREATE TABLE temp_upload_table_#{id} 
          ( id SERIAL, 
            UNIQ_IDENT char(255) NOT NULL, NAME char(255) NOT NULL ); ]
  end

  def copy_query
    uploaded_file = @test_file || file
    %Q[ COPY temp_upload_table_#{id} (#{data_columns.join(',')}) FROM '#{uploaded_file.path}' CSV DELIMITER AS E'#{DATA_DELIMITER}' ENCODING 'UTF8'; ]
  end

  def data_columns
    case data_type
    when 'products'
      ['sku', 'supplier_uniq_ident', 'field_0',
       'field_1', 'field_2', 'field_3', 'field_4',
       'field_5', 'price']
    else
      ['uniq_ident', 'name']
    end
  end

  def insert_products_parsed_data(test=false)
    %Q[ INSERT INTO #{test ? 'temp_test_': ''}products ( #{data_columns.join(',')} )
        SELECT #{data_columns.map{|c| "ps_1.#{c}"}.join(',')}
        FROM temp_upload_table_#{id} as ps_1
          LEFT JOIN temp_upload_table_#{id} as ps_2
          ON (ps_1.sku = ps_2.sku AND ps_1.id < ps_2.id)
        WHERE ps_2.id IS NULL
        ON CONFLICT (sku) DO UPDATE SET
          supplier_uniq_ident = excluded.supplier_uniq_ident,
          #{(0..5).map{|i| "field_#{i} = excluded.field_#{i}" }.join(', ')},
          price = excluded.price ]
  end

  def insert_suppliers_parsed_data(test=false)
    %Q[ INSERT INTO #{test ? 'temp_test_': ''}suppliers ( #{data_columns.join(',')} )
        SELECT #{data_columns.map{|c| "ps_1.#{c}"}.join(',')}
        FROM temp_upload_table_#{id} as ps_1
          LEFT JOIN temp_upload_table_#{id} as ps_2
          ON (ps_1.uniq_ident = ps_2.uniq_ident AND ps_1.id < ps_2.id)
        WHERE ps_2.id IS NULL
        ON CONFLICT (uniq_ident) DO UPDATE SET
          name = excluded.name ]
  end

  def create_test_table!
    %Q[ CREATE TABLE temp_test_#{data_type} AS SELECT * FROM #{data_type} ]
  end

  def start_background_job
    UploadBatchParserCreatorWorker.perform_async(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(:id).page(params[:page])
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def create
    @upload = Upload.new(upload_params[:upload])
    if @upload.save
      flash[:success] = 'File was uploaded and will be processed!'
      redirect_to root_path
    else
      flash[:error] = 'Its few failures when uploading file.'
      render :new
    end
  end

  def index
    @uploads = Upload.order(:id).page(params[:page])
  end

  def new
    @upload = Upload.new
  end

  private

  def upload_params
    params.permit(upload: [:file, :data_type])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en" 
  head
    meta charset="utf-8" 
      meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" 
        meta content="width=device-width, initial-scale=1.0" name="viewport" 
          title= "Uploads"
          = csrf_meta_tags
          /! Le HTML5 shim, for IE6-8 support of HTML elements
          /![if lt IE 9]
            | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script
          = stylesheet_link_tag "application", :media => "all"
          /! For third-generation iPad with high-resolution Retina display:
          /! Size should be 144 x 144 pixels
          = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
          /! For iPhone with high-resolution Retina display:
          /! Size should be 114 x 114 pixels
          = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
          /! For first- and second-generation iPad:
          /! Size should be 72 x 72 pixels
          = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
          /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
          /! Size should be 57 x 57 pixels
          = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
          /! For all other devices
          /! Size should be 32 x 32 pixels
          = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
          = javascript_include_tag "application"
  body
    .container
      .row
        .col-lg-9
          = flash_messages
          = yield
          /! /.well
        /! /span
      /! /row
      br
        br
          footer
            p &copy; Company 2014
    /! /container

app/views/products/index.html.slim
- model_class = Product
.page-header
  h1= t '.title', :default => model_class.model_name.human.pluralize
br
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:sku)
      th= model_class.human_attribute_name(:supplier)
      th= model_class.human_attribute_name(:field_0)
      th= model_class.human_attribute_name(:field_1)
      th= model_class.human_attribute_name(:field_2)
      th= model_class.human_attribute_name(:field_3)
      th= model_class.human_attribute_name(:field_4)
      th= model_class.human_attribute_name(:field_5)
      th= model_class.human_attribute_name(:price)
  tbody
    - @products.each do |product|
      tr
        td= product.id
        td= product.sku
        td= product.supplier_uniq_ident
        td= product.field_0
        td= product.field_1
        td= product.field_2
        td= product.field_3
        td= product.field_4
        td= product.field_5
        td= product.price
br
br
= paginate @products

app/views/uploads/index.html.slim
- model_class = Upload
.page-header
  h1= t '.title', :default => model_class.model_name.human.pluralize
= link_to 'New upload', new_upload_path
br
= link_to 'Products', products_path
br
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:created_at)
      th= model_class.human_attribute_name(:status)
  tbody
    - @uploads.each do |upload|
      tr
        td= upload.id
        td= upload.file_file_name
        td= upload.created_at.strftime("%Y-%m-%d %H:%M")
        td= upload.state
br
br
= paginate @uploads

app/views/uploads/new.html.slim
- model_class = Upload
.page-header
  h1= t '.title', :default => model_class.model_name.human.pluralize
= form_for @upload, html: { multipart: true } do |f|
  - if @upload.errors.any?
    ul
      - @upload.errors.full_messages.each do |message|
        li
          = message
  = f.select :data_type, Upload::DATA_TYPES
  = f.file_field :file
  br
  button.btn.btn-default class = "form-control btn-info" type="submit" style="width:200px" Send